import login from "../swagger/auth/login";

require('dotenv').config();
export = {
  development: {
    /*dialect: "postgres",
    database: process.env.PGSQL_DB_NAME,
    username: process.env.PGSQL_DB_USER,
    password: process.env.PGSQL_DB_PASSWORD,
    host: process.env.PGSQL_DB_HOST,*/
    dialect: "postgres",
    database: process.env.MYSQL_DB_NAME || "db_vedantmf",
    username: process.env.MYSQL_DB_USERNAME || "vedant",
    password: process.env.MYSQL_DB_PASSWORD || "Vedant@2025e3e!Sky#",
    host: process.env.MYSQL_DB_HOST || "216.48.182.224",
    logging: true,
    timezone: "+05:30",
    email: {
      SENDER_EMAIL_HOST: process.env.SMTP_HOST,
      SENDER_EMAIL_PORT: process.env.SMTP_PORT,
      SENDER_EMAIL_ID: process.env.SMTP_USER,
      SENDER_EMAIL_PASSWORD: process.env.SMTP_PASS,
      SMTP_FROM_NAME: process.env.SMTP_FROM_NAME,
      SMTP_FROM_EMAIL: process.env.SMTP_FROM_EMAIL,
    },

    ApiUrl: "http://65.1.140.47/api",
    adminURL: "http://localhost:4200",
    reactUrl: "http://localhost:3000",
    templatePath: "src/template",
    localUrlAccess: "/../../src/public/",
    publicPath: "src/public",
    cryptoKey: "va*proses",
    mfu: {
      baseUrl: process.env.BASE_URL,
      entityId: process.env.ENTITY_ID,
      clientId: process.env.CLIENT_ID,
      clientSecret: process.env.CLIENT_SECRET,
      mfuSecret: process.env.MFU_SECRET,
      mfIv: process.env.MFU_IV,
      accessToken: process.env.API_ACCESS_TOKEN,
      apiCanCreate: process.env.API_CAN_CREATE,
      apiFetchUtrn: process.env.API_FETCH_UTRN,
      apiNormalTxn: process.env.API_NORMAL_TXN_SERVICE,
      apiSystematicTxn: process.env.API_SYSTEMATIC_TXN_SERVICE,
      apiCancellationTxn: process.env.API_CANCELLATION_SERVICE,
      apiTxnAuthdet: process.env.API_TXN_AUTHDET_SERVICE,
      apiTxnApproval: process.env.API_TXN_APPROVAL_SERVICE,
      apiTxnHistory: process.env.API_TXN_HISTORY_SERVICE,
      apiCanValidation: process.env.API_CAN_VAIDATION_SERVICE,
      apiCanFetch: process.env.API_CAN_FETCH_SERVICE,
      apiPrnValidation: process.env.API_PRN_VALIDATION_SERVICE,
      apiBankValidation: process.env.API_BANK_VALIDATION_SERVICE,
      apiSwapPayEez: process.env.API_SWPPAY_EEZ_SERVICE,
      apiCanFolioVal: process.env.API_CAN_FOLIOVAL_SERVICE,
      apiConcentEntry: process.env.API_CONCENT_ENTRY_SERVICE,
      apiConcentView: process.env.API_CONCENT_VIEW_SERVICE,
      apiMfuUtiliyLogin: process.env.API_MFU_UTILITY_API_LOGIN,
      apiEpayEzz: process.env.API_EPAY_EEZ_SERVICE,
      apiEpayEzzStatus: process.env.API_EPAY_EEZ_STATUS_SERVICE,
      apiEpayEzzLogout: process.env.API_EPAY_EEZ_LOGOUT_SERVICE
    },

  },
  staging: {
    dialect: "postgres",
    database: process.env.MYSQL_DB_NAME || "db_vedantmf",
    username: process.env.MYSQL_DB_USERNAME || "vedant",
    password: process.env.MYSQL_DB_PASSWORD || "Vedant@2025e3e!Sky#",
    host: process.env.MYSQL_DB_HOST || "216.48.182.224",
    logging: false,
    timezone: "+05:30",
    email: {
      SENDER_EMAIL_HOST: "smtp-relay.brevo.com",
      SENDER_EMAIL_PORT: "587",
      SENDER_EMAIL_ID: "90f215001@smtp-brevo.com",
      SENDER_EMAIL_PASSWORD: "tNYhXmFDREvJSKU8",
    },
    ApiUrl: "https://prosesenv.com:9065",
    adminURL: "https://prosesenv.com:9065",
    reactUrl: "https://vedant.prosesenv.com",
    templatePath: "template",
    publicPath: "public",
    localUrlAccess: "/../public/",
    cryptoKey: "va*proses",
    mfu: {
      baseUrl: process.env.BASE_URL,
      entityId: process.env.ENTITY_ID,
      clientId: process.env.CLIENT_ID,
      clientSecret: process.env.CLIENT_SECRET,
      mfuSecret: process.env.MFU_SECRET,
      mfIv: process.env.MFU_IV,
      accessToken: process.env.API_ACCESS_TOKEN,
      apiCanCreate: process.env.API_CAN_CREATE,
      apiFetchUtrn: process.env.API_FETCH_UTRN,
      apiNormalTxn: process.env.API_NORMAL_TXN_SERVICE,
      apiSystematicTxn: process.env.API_SYSTEMATIC_TXN_SERVICE,
      apiCancellationTxn: process.env.API_CANCELLATION_SERVICE,
      apiTxnAuthdet: process.env.API_TXN_AUTHDET_SERVICE,
      apiTxnApproval: process.env.API_TXN_APPROVAL_SERVICE,
      apiTxnHistory: process.env.API_TXN_HISTORY_SERVICE,
      apiCanValidation: process.env.API_CAN_VAIDATION_SERVICE,
      apiCanFetch: process.env.API_CAN_FETCH_SERVICE,
      apiPrnValidation: process.env.API_PRN_VALIDATION_SERVICE,
      apiBankValidation: process.env.API_BANK_VALIDATION_SERVICE,
      apiSwapPayEez: process.env.API_SWPPAY_EEZ_SERVICE,
      apiCanFolioVal: process.env.API_CAN_FOLIOVAL_SERVICE,
      apiConcentEntry: process.env.API_CONCENT_ENTRY_SERVICE,
      apiConcentView: process.env.API_CONCENT_VIEW_SERVICE
    },
  },
  production: {
    dialect: "postgres",
    database: process.env.PGSQL_DB_NAME,
    username: process.env.PGSQL_DB_USER,
    password: process.env.PGSQL_DB_PASSWORD,
    host: process.env.PGSQL_DB_HOST,
    logging: false,
    timezone: "+05:30",
    email: {
      SENDER_EMAIL_HOST: process.env.SMTP_HOST,
      SENDER_EMAIL_PORT: process.env.SMTP_PORT,
      SENDER_EMAIL_ID: process.env.SMTP_USER,
      SENDER_EMAIL_PASSWORD: process.env.SMTP_PASS,
      SMTP_FROM_NAME: process.env.SMTP_FROM_NAME,
      SMTP_FROM_EMAIL: process.env.SMTP_FROM_EMAIL,
    },
    ApiUrl: "http://localhost:9065",
    //ApiUrl: "https://preprod.vedantmf.com/api/",
    adminURL: "http://localhost:4200",
    reactUrl: "https://vedantmf.com",
    templatePath: "template",
    publicPath: "public",
    localUrlAccess: "/../public/",
    cryptoKey: "va*proses",
    mfu: {
      baseUrl: process.env.BASE_URL,
      entityId: process.env.ENTITY_ID,
      clientId: process.env.CLIENT_ID,
      clientSecret: process.env.CLIENT_SECRET,
      mfuSecret: process.env.MFU_SECRET,
      mfIv: process.env.MFU_IV,
      loginId: process.env.MFU_LOGIN_ID,
      password: process.env.MFU_PASSWORD,
      accessToken: process.env.API_ACCESS_TOKEN,
      apiCanCreate: process.env.API_CAN_CREATE,
      apiFetchUtrn: process.env.API_FETCH_UTRN,
      apiNormalTxn: process.env.API_NORMAL_TXN_SERVICE,
      apiSystematicTxn: process.env.API_SYSTEMATIC_TXN_SERVICE,
      apiCancellationTxn: process.env.API_CANCELLATION_SERVICE,
      apiTxnAuthdet: process.env.API_TXN_AUTHDET_SERVICE,
      apiTxnApproval: process.env.API_TXN_APPROVAL_SERVICE,
      apiTxnHistory: process.env.API_TXN_HISTORY_SERVICE,
      apiCanValidation: process.env.API_CAN_VAIDATION_SERVICE,
      apiCanFetch: process.env.API_CAN_FETCH_SERVICE,
      apiPrnValidation: process.env.API_PRN_VALIDATION_SERVICE,
      apiBankValidation: process.env.API_BANK_VALIDATION_SERVICE,
      apiSwapPayEez: process.env.API_SWPPAY_EEZ_SERVICE,
      apiCanFolioVal: process.env.API_CAN_FOLIOVAL_SERVICE,
      apiConcentEntry: process.env.API_CONCENT_ENTRY_SERVICE,
      apiConcentView: process.env.API_CONCENT_VIEW_SERVICE,
      apiMfuUtiliyLogin: process.env.API_MFU_UTILITY_API_LOGIN,
      apiEpayEzz: process.env.API_EPAY_EEZ_SERVICE,
      apiEpayEzzStatus: process.env.API_EPAY_EEZ_STATUS_SERVICE,
      apiEpayEzzLogout: process.env.API_EPAY_EEZ_LOGOUT_SERVICE
    },
  },

};
